### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by mitburr** [JustenRickert/shinobi#1]
•`_´•

**Comment by JustenRickert** [comment]
Lol okay one sec

**Comment by JustenRickert** [comment]
Okay I've added a readme. Let me know if that's enough to help you get things running. I'm not sure that things are in a place where contribution is possible yet. But maybe in a little bit. I've created some conceptual hurdles that I'm curious of other peoples' opinions on. Like my `IR`s in particular. I'm trying to find to find utilities that represent state changes well, and don't compromise the typing system. See example:

```typescript
function purchaseShinobi(id: ShinobiId) {
  setGameState((state) => {
    const s = state.shop.shinobi.get(id);
    return deepMerge(state, {
      shop: {
        lastRolledTime: state.gameTime,
        shinobi: state.shop.shinobi.remove(id), // `shinobi.remove` returns a `new IR` with the `id` shinobi removed 
      },
      points: state.points - s.cost,
      shinobi: state.shinobi.add(s), // `shinobi.add` returns a `new IR` with the `id` shinobi added.
    });
  });
}
```

**Comment by mitburr** [comment]
Will report back today
